#!/usr/bin/env python3
"""
ag-devops unified scaffold CLI - v2.0.0

Generates Helm template fragments and CI/CD configs from BC Gov AG templates.
All resource types are handled by this single script via the --type flag.

Usage:
    python scaffold.py --type deployment --name web-api --port 8080 [--output-dir gitops/templates]
    python scaffold.py --type networkpolicy --name web-api --ingress-from-router --egress-to-apps postgresql:5432
    python scaffold.py --type docker-ci --image my-app --registry ghcr.io/my-org [--output-dir .github/workflows]
    python scaffold.py --type deployment --name web-api --dry-run        # preview only
    python scaffold.py --type service --name web-api --force             # overwrite existing

Safety features:
    - Post-render validation: fails if any @@MARKER@@ remains unreplaced
    - Path traversal guard: --output-dir must be within the working directory
    - Idempotency: skips existing files unless --force is given
    - Kubernetes name validation: names must match ^[a-z][a-z0-9-]{1,62}$
    - Dry-run mode: prints what would be written without touching the filesystem
"""

import argparse
import os
import re
import sys

PLUGIN_VERSION = "2.0.0"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def to_camel(name: str) -> str:
    """Convert kebab-case or snake_case to camelCase (Helm values key)."""
    parts = re.split(r"[-_]", name)
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def validate_k8s_name(name: str) -> None:
    """Fail fast if name does not meet Kubernetes naming rules."""
    if not re.match(r"^[a-z][a-z0-9-]{1,62}$", name):
        sys.exit(
            f"ERROR: '{name}' is not a valid Kubernetes name. "
            "Must start with a lowercase letter, contain only [a-z0-9-], and be 2–63 characters."
        )


def guard_output_dir(output_dir: str) -> str:
    """Resolve and validate that output_dir is inside the current working directory."""
    cwd = os.path.realpath(os.getcwd())
    resolved = os.path.realpath(os.path.abspath(output_dir))
    try:
        common = os.path.commonpath([cwd, resolved])
    except ValueError:
        common = ""
    if common != cwd:
        sys.exit(
            f"ERROR: --output-dir '{output_dir}' resolves to '{resolved}' which is outside "
            f"the current working directory '{cwd}'. Refusing to write."
        )
    return resolved


def find_template_dir() -> str:
    """Locate the assets/templates directory relative to this script (handles symlinks)."""
    script_dir = os.path.dirname(os.path.realpath(__file__))
    # Try plugin root layout: scripts/ is sibling of assets/
    candidate = os.path.join(script_dir, "..", "assets", "templates")
    if os.path.isdir(candidate):
        return os.path.abspath(candidate)
    sys.exit(
        f"ERROR: Cannot find assets/templates directory relative to script at '{script_dir}'. "
        "Ensure the plugin structure is intact."
    )


def load_template(template_dir: str, filename: str) -> str:
    path = os.path.join(template_dir, filename)
    if not os.path.isfile(path):
        sys.exit(f"ERROR: Template not found: {path}")
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def render(tpl: str, replacements: dict) -> str:
    for marker, value in replacements.items():
        tpl = tpl.replace(marker, str(value))
    return tpl


def guard_unreplaced_markers(content: str, output_path: str) -> None:
    """Fail if any @@MARKER@@ placeholders survive rendering."""
    remaining = re.findall(r"@@\w+@@", content)
    if remaining:
        unique = sorted(set(remaining))
        sys.exit(
            f"ERROR: Rendering produced unreplaced markers in '{output_path}': {unique}\n"
            "This means required arguments were not provided. Run with --help to see all options."
        )


def traceability_header(resource_type: str) -> str:
    return (
        f"# Generated by ag-devops v{PLUGIN_VERSION} - scaffold.py --type {resource_type}\n"
        "# DO NOT EDIT MANUALLY - re-run scaffold.py to regenerate\n"
    )


def write_or_dry_run(output_path: str, content: str, dry_run: bool, force: bool) -> None:
    if dry_run:
        print(f"[DRY-RUN] Would write: {output_path}")
        print("--- content preview ---")
        print(content[:800] + ("..." if len(content) > 800 else ""))
        print("--- end preview ---")
        return

    if os.path.exists(output_path) and not force:
        print(f"SKIPPED (already exists): {output_path}  -- use --force to overwrite")
        return

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"Written: {output_path}")


# ---------------------------------------------------------------------------
# NetworkPolicy builder (programmatic - no template file needed)
# ---------------------------------------------------------------------------

def build_networkpolicy(args) -> str:
    """Build NetworkPolicy Helm template content from CLI flags."""
    lines = [
        '{{- $np := dict "Values" .Values -}}',
        '{{- $_ := set $np "ApplicationGroup" .Values.project -}}',
        f'{{{{- $_ := set $np "Name" "{args.name}" -}}}}',
        '{{- $_ := set $np "Namespace" $.Release.Namespace -}}',
    ]

    # Policy types
    has_ingress = args.ingress_from_router or bool(args.ingress_from_apps)
    has_egress = bool(args.egress_to_apps) or bool(args.egress_to_cidr) or args.egress_internet
    policy_types = " ".join(
        f'"{t}"' for t in (["Ingress"] if has_ingress else []) + (["Egress"] if has_egress else [])
    ) or '"Ingress"'
    lines.append(f'{{{{- $_ := set $np "PolicyTypes" (list {policy_types}) -}}}}')

    # Internet egress annotations
    if args.egress_internet:
        if not args.justification or not args.approved_by:
            sys.exit("ERROR: --justification and --approved-by are required with --egress-internet")
        lines.append(
            f'{{{{- $_ := set $np "Annotations" (dict\n'
            f'  "justification" "{args.justification}"\n'
            f'  "approvedBy"    "{args.approved_by}"\n'
            f') -}}}}'
        )

    # AllowIngressFrom block
    if has_ingress:
        app_names = [a.strip() for a in args.ingress_from_apps.split(",") if a.strip()] if args.ingress_from_apps else []
        block = ['{{- $_ := set $np "AllowIngressFrom" (dict', f'  "ports" (list {args.port})']
        if app_names:
            items = "\n".join(f'    (dict "name" "{a}")' for a in app_names)
            block.append(f'  "apps" (list\n{items}\n  )')
        if args.ingress_from_router:
            block.append(
                '  "namespaces" (list (dict\n'
                '    "name" "openshift-ingress"\n'
                '    "podSelector" (dict "matchLabels" (dict\n'
                '      "ingresscontroller.operator.openshift.io/deployment-ingresscontroller" "default"\n'
                '    ))\n'
                '  ))'
            )
        block.append(") -}}")
        lines.append("\n".join(block))

    # AllowEgressTo block
    if has_egress:
        app_pairs, cidr_entries = [], []
        if args.egress_to_apps:
            for pair in args.egress_to_apps.split(","):
                pair = pair.strip()
                if ":" not in pair:
                    sys.exit(f"ERROR: --egress-to-apps value '{pair}' must be name:port")
                app_name, port = pair.rsplit(":", 1)
                app_pairs.append((app_name.strip(), int(port.strip())))
        if args.egress_to_cidr:
            for entry in args.egress_to_cidr.split(","):
                entry = entry.strip()
                if ":" not in entry:
                    sys.exit(f"ERROR: --egress-to-cidr value '{entry}' must be cidr:port")
                cidr, port = entry.rsplit(":", 1)
                cidr_entries.append((cidr.strip(), int(port.strip())))

        block = ['{{- $_ := set $np "AllowEgressTo" (dict']
        if app_pairs:
            items = "\n".join(
                f'    (dict\n      "name" "{n}"\n      "ports" (list (dict "port" {p} "protocol" "TCP"))\n    )'
                for n, p in app_pairs
            )
            block.append(f'  "apps" (list\n{items}\n  )')
        if cidr_entries:
            items = "\n".join(
                f'    (dict\n      "cidr" "{c}"\n      "ports" (list {p})\n    )'
                for c, p in cidr_entries
            )
            block.append(f'  "ipBlocks" (list\n{items}\n  )')
        if args.egress_internet:
            block.append(
                '  "internet" (dict\n    "enabled" true\n    "cidrs" (list "0.0.0.0/0")\n    "ports" (list 443)\n  )'
            )
        block.append(") -}}")
        lines.append("\n".join(block))

    lines.append('{{ include "ag-template.networkpolicy" $np }}')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Type configuration registry
# ---------------------------------------------------------------------------

# Each entry: template filename, output filename lambda, default output dir, marker builder lambda
TYPE_CONFIGS = {
    "deployment": {
        "template": "deployment.tpl.yaml",
        "output": lambda a: f"{a.name}-deployment.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@PORT@@": str(a.port),
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@PROBE_LIVE_PATH@@": a.probe_live_path,
            "@@PROBE_READY_PATH@@": a.probe_ready_path,
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            f"#   dataClass: {a.data_class}",
            "#   resources:",
            "#     requests: { cpu: 50m, memory: 128Mi }",
            "#     limits:   { cpu: 500m, memory: 512Mi }",
        ],
    },
    "service": {
        "template": "service.tpl.yaml",
        "output": lambda a: f"{a.name}-service.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@PORT@@": str(a.port),
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": None,
    },
    "route": {
        "template": "route.tpl.yaml",
        "output": lambda a: f"{a.name}-route.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            "#   route:",
            "#     enabled: true",
            f"#     host: {a.host or '<project>-<env>.apps.emerald.devops.gov.bc.ca'}",
            "#     annotations:",
            f"#       aviinfrasetting.ako.vmware.com/name: dataclass-{a.data_class}",
        ],
    },
    "hpa": {
        "template": "hpa.tpl.yaml",
        "output": lambda a: f"{a.name}-hpa.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            "#   hpa:",
            f"#     minReplicas: {a.min_replicas}",
            f"#     maxReplicas: {a.max_replicas}",
            f"#     targetAverageUtilizationCpu: {a.cpu_utilization}",
        ],
    },
    "pdb": {
        "template": "pdb.tpl.yaml",
        "output": lambda a: f"{a.name}-pdb.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            "#   pdb:",
            f"#     maxUnavailable: {a.max_unavailable}",
        ],
    },
    "statefulset": {
        "template": "statefulset.tpl.yaml",
        "output": lambda a: f"{a.name}-statefulset.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@PORT@@": str(a.port),
            "@@SERVICE_NAME@@": a.service_name or a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@PROBE_LIVE_PATH@@": a.probe_live_path,
            "@@PROBE_READY_PATH@@": a.probe_ready_path,
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            f"#   dataClass: {a.data_class}",
        ],
    },
    "ingress": {
        "template": "ingress.tpl.yaml",
        "output": lambda a: f"{a.name}-ingress.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@HOST@@": a.host or f"{a.name}.apps.emerald.devops.gov.bc.ca",
            "@@PATH@@": a.path,
            "@@SERVICE_PORT@@": str(a.service_port or a.port),
            "@@AVI_CLASS@@": a.avi_class,
        },
        "values_hint": None,
    },
    "pvc": {
        "template": "pvc.tpl.yaml",
        "output": lambda a: f"{a.name}-pvc.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@SIZE@@": a.size,
            "@@STORAGE_CLASS@@": a.storage_class,
            "@@ACCESS_MODE@@": a.access_mode,
        },
        "values_hint": None,
    },
    "job": {
        "template": "job.tpl.yaml",
        "output": lambda a: f"{a.name}-job.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@BACKOFF_LIMIT@@": str(a.backoff_limit),
            "@@TTL@@": str(a.ttl),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            f"#   dataClass: {a.data_class}",
        ],
    },
    "serviceaccount": {
        "template": "serviceaccount.tpl.yaml",
        "output": lambda a: f"{a.name}-serviceaccount.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": None,
    },
    "configmap": {
        "template": "configmap.tpl.yaml",
        "output": lambda a: f"{a.name}-configmap.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            "#   configMap:",
            "#     KEY: value",
        ],
    },
    "cronjob": {
        "template": "cronjob.tpl.yaml",
        "output": lambda a: f"{a.name}-cronjob.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
            "@@SCHEDULE@@": a.schedule,
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            f"#   dataClass: {a.data_class}",
        ],
    },
    "externalsecret": {
        "template": "externalsecret.tpl.yaml",
        "output": lambda a: f"{a.name}-externalsecret.yaml",
        "default_dir": "gitops/templates",
        "markers": lambda a: {
            "@@NAME@@": a.name,
            "@@VALUES_KEY@@": to_camel(a.name),
        },
        "values_hint": lambda a: [
            f"# Add to values.yaml under {to_camel(a.name)}:",
            f"# {to_camel(a.name)}:",
            "#   externalSecret:",
            "#     secretStoreName: vault",
            "#     keys:",
            "#       - remoteRef: secret/path/MY_SECRET",
            "#         secretKey: MY_SECRET",
        ],
    },
    "docker-ci": {
        "template": "docker.tpl.yml",
        "output": lambda a: f"{a.image}-docker.yml",
        "default_dir": ".github/workflows",
        "markers": lambda a: {
            "@@IMAGE@@": a.image,
            "@@REGISTRY@@": a.registry,
            "@@CONTEXT@@": a.context,
            "@@FILE@@": a.file,
            "@@PLATFORMS@@": a.platforms,
        },
        "values_hint": None,
    },
    "sast-ci": {
        "template": "sast.tpl.yml",
        "output": lambda a: "sast.yml",
        "default_dir": ".github/workflows",
        "markers": lambda a: {
            "@@PROJECT_KEY@@": a.project_key,
            "@@SONAR_HOST@@": a.sonar_host,
            "@@COVERAGE_REPORT@@": a.coverage_report,
            "@@SOURCES@@": a.sources,
        },
        "values_hint": None,
    },
}

ALL_TYPES = sorted(TYPE_CONFIGS.keys()) + ["networkpolicy"]


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=f"ag-devops scaffold CLI v{PLUGIN_VERSION} - generate Helm templates and CI configs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"Available types: {', '.join(ALL_TYPES)}",
    )

    p.add_argument("--type", required=True, choices=ALL_TYPES, metavar="TYPE",
                   help=f"Resource type to scaffold. One of: {', '.join(ALL_TYPES)}")
    p.add_argument("--output-dir", default=None,
                   help="Output directory (default varies by type)")
    p.add_argument("--dry-run", action="store_true",
                   help="Preview output without writing files")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing files (default: skip with warning)")

    # Common identity args
    p.add_argument("--name", default="", help="Component name (kebab-case, e.g. web-api)")
    p.add_argument("--port", type=int, default=8080, help="Container/service port (default: 8080)")
    p.add_argument("--data-class", default="low", choices=["low", "medium", "high"],
                   help="Data classification (default: low)")

    # Deployment / statefulset
    p.add_argument("--probe-live-path", default="/health/live",
                   help="Liveness probe HTTP path (default: /health/live)")
    p.add_argument("--probe-ready-path", default="/health/ready",
                   help="Readiness probe HTTP path (default: /health/ready)")
    p.add_argument("--service-name", default="",
                   help="Headless service name for StatefulSet (default: same as --name)")

    # HPA
    p.add_argument("--min-replicas", type=int, default=1, help="HPA minimum replicas (default: 1)")
    p.add_argument("--max-replicas", type=int, default=3, help="HPA maximum replicas (default: 3)")
    p.add_argument("--cpu-utilization", type=int, default=70, help="HPA CPU target %% (default: 70)")

    # PDB
    p.add_argument("--max-unavailable", default="25%%", help="PDB maxUnavailable (default: 25%%)")

    # Route / Ingress
    p.add_argument("--host", default="", help="Hostname for Route or Ingress")
    p.add_argument("--path", default="/", help="Ingress path (default: /)")
    p.add_argument("--service-port", type=int, default=0,
                   help="Ingress backend service port (default: same as --port)")
    p.add_argument("--avi-class", default="dataclass-low",
                   help="AVI infra setting name (default: dataclass-low)")

    # PVC
    p.add_argument("--size", default="1Gi", help="PVC storage size (default: 1Gi)")
    p.add_argument("--storage-class", default="netapp-block-standard",
                   help="StorageClass name (default: netapp-block-standard)")
    p.add_argument("--access-mode", default="ReadWriteOnce",
                   choices=["ReadWriteOnce", "ReadWriteMany", "ReadOnlyMany"],
                   help="PVC access mode (default: ReadWriteOnce)")

    # Job
    p.add_argument("--backoff-limit", type=int, default=3, help="Job backoffLimit (default: 3)")
    p.add_argument("--ttl", type=int, default=300, help="Job ttlSecondsAfterFinished (default: 300)")

    # NetworkPolicy
    p.add_argument("--ingress-from-router", action="store_true",
                   help="Allow ingress from OpenShift router")
    p.add_argument("--ingress-from-apps", default="",
                   help="Comma-separated app names allowed to send traffic to this component")
    p.add_argument("--egress-to-apps", default="",
                   help="Comma-separated name:port pairs for egress to other apps, e.g. postgresql:5432")
    p.add_argument("--egress-to-cidr", default="",
                   help="Comma-separated cidr:port pairs, e.g. 142.34.208.0/24:443")
    p.add_argument("--egress-internet", action="store_true",
                   help="Allow internet-wide egress -- requires --justification and --approved-by")
    p.add_argument("--justification", default="",
                   help="Required with --egress-internet")
    p.add_argument("--approved-by", default="",
                   help="Required with --egress-internet: approver name or ticket ref")

    # CronJob
    p.add_argument("--schedule", default="0 2 * * *", help="Cron schedule expression (default: 0 2 * * *)")

    # Docker CI
    p.add_argument("--image", default="", help="Image name for Docker CI workflow")
    p.add_argument("--registry", default="", help="Container registry, e.g. ghcr.io/bcgov-c")
    p.add_argument("--context", default=".", help="Docker build context (default: .)")
    p.add_argument("--file", default="Dockerfile", help="Dockerfile path (default: Dockerfile)")
    p.add_argument("--platforms", default="linux/amd64",
                   help="Build platforms (default: linux/amd64)")

    # SAST CI
    p.add_argument("--project-key", default="", help="SonarQube project key")
    p.add_argument("--sonar-host", default="", help="SonarQube server URL")
    p.add_argument("--coverage-report", default="coverage/lcov.info",
                   help="Coverage report path (default: coverage/lcov.info)")
    p.add_argument("--sources", default=".", help="Source root for SAST scan (default: .)")

    return p


# ---------------------------------------------------------------------------
# Validation per type
# ---------------------------------------------------------------------------

REQUIRED_BY_TYPE = {
    "deployment":     ["name"],
    "service":        ["name"],
    "route":          ["name"],
    "hpa":            ["name"],
    "pdb":            ["name"],
    "statefulset":    ["name"],
    "ingress":        ["name", "host"],
    "pvc":            ["name"],
    "job":            ["name"],
    "serviceaccount": ["name"],
    "configmap":      ["name"],
    "cronjob":        ["name"],
    "externalsecret": ["name"],
    "networkpolicy":  ["name"],
    "docker-ci":      ["image", "registry"],
    "sast-ci":        ["project-key", "sonar-host"],
}


def validate_required(args) -> None:
    missing = []
    for field in REQUIRED_BY_TYPE.get(args.type, []):
        attr = field.replace("-", "_")
        if not getattr(args, attr, ""):
            missing.append(f"--{field}")
    if missing:
        sys.exit(f"ERROR: The following arguments are required for --type {args.type}: {', '.join(missing)}")

    # Validate Kubernetes names
    if args.type not in ("docker-ci", "sast-ci") and args.name:
        validate_k8s_name(args.name)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    validate_required(args)

    # Resolve output directory
    cfg = TYPE_CONFIGS.get(args.type)
    default_dir = cfg["default_dir"] if cfg else "gitops/templates"
    output_dir = guard_output_dir(args.output_dir or default_dir)

    # NetworkPolicy is fully programmatic
    if args.type == "networkpolicy":
        content = traceability_header("networkpolicy") + build_networkpolicy(args)
        out_path = os.path.join(output_dir, f"{args.name}-networkpolicy.yaml")
        write_or_dry_run(out_path, content, args.dry_run, args.force)
        return

    # Template-based types
    template_dir = find_template_dir()
    tpl_raw = load_template(template_dir, cfg["template"])
    replacements = cfg["markers"](args)
    content = render(tpl_raw, replacements)

    out_filename = cfg["output"](args)
    out_path = os.path.join(output_dir, out_filename)

    guard_unreplaced_markers(content, out_path)
    content = traceability_header(args.type) + content

    write_or_dry_run(out_path, content, args.dry_run, args.force)

    # Values hint
    if cfg.get("values_hint") and not args.dry_run:
        print()
        for line in cfg["values_hint"](args):
            print(line)


if __name__ == "__main__":
    main()
