"""
Test harness for ag-devops scaffold.py

Verifies that `scaffold.py --type X` produces:
  1. Valid YAML (parseable by PyYAML)
  2. No unreplaced @@MARKER@@ tokens
  3. Expected Helm/content fragments per type
  4. Correct output filename and default output directory

Run with:
    pytest tests/ -v
    pytest tests/ -v --update-fixtures   # regenerate golden files
"""

import os
import re
import subprocess
import sys
import shutil
import tempfile
from pathlib import Path

import pytest
import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).parent.parent.resolve()
SCAFFOLD = REPO_ROOT / "plugins" / "ag-devops" / "scripts" / "scaffold.py"
FIXTURES = Path(__file__).parent / "fixtures" / "expected"
# Test output dirs go inside the repo to satisfy the path traversal guard
TEST_OUTPUT_BASE = Path(__file__).parent / "output"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def in_repo_root():
    """Ensure CWD is the repo root for all tests (path traversal guard requires this)."""
    old = os.getcwd()
    os.chdir(REPO_ROOT)
    yield
    os.chdir(old)


@pytest.fixture
def scaffold_out_dir(request):
    """Create a unique output dir relative to REPO_ROOT (satisfies path traversal guard)."""
    test_name = re.sub(r"[^a-zA-Z0-9_-]", "_", request.node.name)[:50]
    rel = Path("tests") / "output" / test_name
    abs_d = REPO_ROOT / rel
    abs_d.mkdir(parents=True, exist_ok=True)
    yield rel  # yield RELATIVE path so scaffold.py resolves it against its own cwd=REPO_ROOT
    shutil.rmtree(abs_d, ignore_errors=True)


def run_scaffold(*extra_args, expect_fail=False, output_dir=None):
    """Run scaffold.py with given args; return (stdout, stderr, returncode)."""
    cmd = [sys.executable, str(SCAFFOLD)]
    if output_dir:
        cmd += ["--output-dir", str(output_dir)]
    cmd += list(extra_args)
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO_ROOT))
    if not expect_fail and result.returncode != 0:
        pytest.fail(
            f"scaffold.py failed (rc={result.returncode}):\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout, result.stderr, result.returncode


def read_output(output_dir, filename):
    """Read the generated file from output_dir (relative to REPO_ROOT)."""
    path = REPO_ROOT / output_dir / filename
    assert path.exists(), f"Expected output file not found: {path}"
    return path.read_text(encoding="utf-8")


def assert_no_markers(content, filename=""):
    """Assert no @@MARKER@@ tokens remain in rendered content."""
    remaining = re.findall(r"@@\w+@@", content)
    assert not remaining, f"Unreplaced markers in {filename}: {remaining}"


def assert_valid_yaml(content, filename=""):
    """Assert content is parseable YAML (may be multi-document)."""
    try:
        list(yaml.safe_load_all(content))
    except yaml.YAMLError as exc:
        pytest.fail(f"Invalid YAML in {filename}:\n{exc}\n\nContent:\n{content}")


def save_or_compare_fixture(name, content, update):
    """Save as golden fixture or compare against existing."""
    fixture_path = FIXTURES / name
    if update or not fixture_path.exists():
        FIXTURES.mkdir(parents=True, exist_ok=True)
        fixture_path.write_text(content, encoding="utf-8")
        print(f"  [fixture saved] {fixture_path.name}")
    else:
        expected = fixture_path.read_text(encoding="utf-8")
        # Strip traceability header lines for comparison (they contain version)
        def strip_header(s):
            lines = s.splitlines(keepends=True)
            return "".join(l for l in lines if not l.startswith("# Generated by ag-devops") and not l.startswith("# DO NOT EDIT"))
        assert strip_header(content) == strip_header(expected), (
            f"Output differs from fixture {fixture_path.name}.\n"
            "Re-run with --update-fixtures to regenerate."
        )


# ---------------------------------------------------------------------------
# Helm template types (YAML output)
# ---------------------------------------------------------------------------

HELM_TYPES = [
    ("deployment",     "my-api",     ["--name", "my-api", "--port", "8080"],              "my-api-deployment.yaml"),
    ("service",        "my-api",     ["--name", "my-api", "--port", "8080"],              "my-api-service.yaml"),
    ("route",          "my-api",     ["--name", "my-api"],                                "my-api-route.yaml"),
    ("statefulset",    "pg",         ["--name", "pg", "--port", "5432"],                  "pg-statefulset.yaml"),
    ("hpa",            "my-api",     ["--name", "my-api"],                                "my-api-hpa.yaml"),
    ("pdb",            "my-api",     ["--name", "my-api"],                                "my-api-pdb.yaml"),
    ("ingress",        "my-api",     ["--name", "my-api", "--host", "my-api.example.com"],"my-api-ingress.yaml"),
    ("pvc",            "pg-data",    ["--name", "pg-data"],                               "pg-data-pvc.yaml"),
    ("job",            "db-migrate", ["--name", "db-migrate"],                            "db-migrate-job.yaml"),
    ("serviceaccount", "my-api",     ["--name", "my-api"],                                "my-api-serviceaccount.yaml"),
    ("configmap",      "my-api",     ["--name", "my-api"],                                "my-api-configmap.yaml"),
    ("cronjob",        "my-task",    ["--name", "my-task", "--schedule", "0 2 * * *"],    "my-task-cronjob.yaml"),
    ("externalsecret", "my-api",     ["--name", "my-api"],                                "my-api-externalsecret.yaml"),
]

@pytest.mark.parametrize("rtype,name,extra_args,expected_file", HELM_TYPES,
                         ids=[t[0] for t in HELM_TYPES])
def test_helm_type_produces_valid_output(rtype, name, extra_args, expected_file, update_fixtures, scaffold_out_dir):
    """Each Helm template type produces valid YAML with no unreplaced markers."""
    stdout, stderr, rc = run_scaffold("--type", rtype, *extra_args, output_dir=scaffold_out_dir)

    content = read_output(scaffold_out_dir, expected_file)
    assert_no_markers(content, expected_file)
    assert_valid_yaml(content, expected_file)

    # Traceability header
    assert f"scaffold.py --type {rtype}" in content, "Missing traceability header"
    # Component name appears in content
    assert name in content, f"Component name '{name}' not found in output"

    save_or_compare_fixture(expected_file, content, update_fixtures)


# ---------------------------------------------------------------------------
# CI workflow types (YAML output)
# ---------------------------------------------------------------------------

CI_TYPES = [
    ("docker-ci", "app", ["--image", "my-app", "--registry", "ghcr.io/bcgov-c"], "my-app-docker.yml"),
    ("sast-ci",   "sast", ["--project-key", "my-proj", "--sonar-host", "https://sonar.example.com"], "sast.yml"),
]

@pytest.mark.parametrize("rtype,label,extra_args,expected_file", CI_TYPES,
                         ids=[t[0] for t in CI_TYPES])
def test_ci_type_produces_valid_output(rtype, label, extra_args, expected_file, update_fixtures, scaffold_out_dir):
    """CI workflow types produce valid YAML with no unreplaced markers."""
    stdout, stderr, rc = run_scaffold("--type", rtype, *extra_args, output_dir=scaffold_out_dir)

    content = read_output(scaffold_out_dir, expected_file)
    assert_no_markers(content, expected_file)
    assert_valid_yaml(content, expected_file)
    assert f"scaffold.py --type {rtype}" in content

    save_or_compare_fixture(expected_file, content, update_fixtures)


# ---------------------------------------------------------------------------
# NetworkPolicy (programmatic, no template file)
# ---------------------------------------------------------------------------

def test_networkpolicy_ingress_from_router(update_fixtures, scaffold_out_dir):
    """NetworkPolicy with --ingress-from-router produces valid template."""
    stdout, stderr, rc = run_scaffold(
        "--type", "networkpolicy",
        "--name", "my-api",
        "--port", "8080",
        "--ingress-from-router",
        output_dir=scaffold_out_dir,
    )
    content = read_output(scaffold_out_dir, "my-api-networkpolicy.yaml")
    assert_no_markers(content, "my-api-networkpolicy.yaml")
    assert "AllowIngressFrom" in content
    assert "openshift-ingress" in content
    assert "my-api" in content
    save_or_compare_fixture("my-api-networkpolicy.yaml", content, update_fixtures)


def test_networkpolicy_egress_to_apps(scaffold_out_dir):
    """NetworkPolicy with --egress-to-apps produces AllowEgressTo block."""
    run_scaffold(
        "--type", "networkpolicy",
        "--name", "my-api",
        "--port", "8080",
        "--egress-to-apps", "postgresql:5432",
        output_dir=scaffold_out_dir,
    )
    content = read_output(scaffold_out_dir, "my-api-networkpolicy.yaml")
    assert_no_markers(content)
    assert "AllowEgressTo" in content
    assert "postgresql" in content


def test_networkpolicy_internet_egress_requires_approval(scaffold_out_dir):
    """--egress-internet without --justification and --approved-by must fail."""
    _, _, rc = run_scaffold(
        "--type", "networkpolicy",
        "--name", "my-api",
        "--egress-internet",
        output_dir=scaffold_out_dir,
        expect_fail=True,
    )
    assert rc != 0, "Should fail without --justification and --approved-by"


def test_networkpolicy_internet_egress_with_approval(scaffold_out_dir):
    """--egress-internet with required annotations should succeed."""
    run_scaffold(
        "--type", "networkpolicy",
        "--name", "my-api",
        "--port", "443",
        "--egress-internet",
        "--justification", "External OAuth provider",
        "--approved-by", "JIRA-1234",
        output_dir=scaffold_out_dir,
    )
    content = read_output(scaffold_out_dir, "my-api-networkpolicy.yaml")
    assert "justification" in content
    assert "approvedBy" in content


# ---------------------------------------------------------------------------
# Safety feature tests
# ---------------------------------------------------------------------------

def test_invalid_k8s_name_rejected(scaffold_out_dir):
    """Names violating Kubernetes naming rules must fail."""
    _, _, rc = run_scaffold(
        "--type", "deployment",
        "--name", "My-App",  # uppercase not allowed
        output_dir=scaffold_out_dir,
        expect_fail=True,
    )
    assert rc != 0


def test_path_traversal_rejected():
    """--output-dir outside cwd should be rejected."""
    _, _, rc = run_scaffold(
        "--type", "service",
        "--name", "my-api",
        "--output-dir", "C:\\Windows\\Temp\\outside",
        expect_fail=True,
    )
    assert rc != 0


def test_dry_run_does_not_write(scaffold_out_dir):
    """--dry-run must print preview without writing any file."""
    stdout, _, _ = run_scaffold(
        "--type", "deployment",
        "--name", "my-api",
        "--port", "8080",
        "--dry-run",
        output_dir=scaffold_out_dir,
    )
    assert "[DRY-RUN]" in stdout
    # No file should be written
    abs_dir = REPO_ROOT / scaffold_out_dir
    files = list(abs_dir.iterdir()) if abs_dir.exists() else []
    assert len(files) == 0, f"Files were written in dry-run mode: {files}"


def test_force_overwrites_existing(scaffold_out_dir):
    """--force should overwrite; without --force, existing file is skipped."""
    args = ["--type", "service", "--name", "my-api", "--port", "8080"]
    run_scaffold(*args, output_dir=scaffold_out_dir)

    # Without --force: skipped
    stdout, _, _ = run_scaffold(*args, output_dir=scaffold_out_dir)
    assert "SKIPPED" in stdout

    # With --force: no "Skipped" message
    stdout, _, _ = run_scaffold(*args, "--force", output_dir=scaffold_out_dir)
    assert "SKIPPED" not in stdout


def test_missing_required_arg_fails(scaffold_out_dir):
    """Missing required argument (e.g. --name for deployment) should fail."""
    _, _, rc = run_scaffold(
        "--type", "deployment",
        # missing --name
        output_dir=scaffold_out_dir,
        expect_fail=True,
    )
    assert rc != 0


# ---------------------------------------------------------------------------
# Deployment probe paths
# ---------------------------------------------------------------------------

def test_deployment_custom_probe_paths(scaffold_out_dir):
    """Custom probe paths are correctly substituted in deployment template."""
    run_scaffold(
        "--type", "deployment",
        "--name", "my-api",
        "--port", "9090",
        "--probe-live-path", "/actuator/health/liveness",
        "--probe-ready-path", "/actuator/health/readiness",
        output_dir=scaffold_out_dir,
    )
    content = read_output(scaffold_out_dir, "my-api-deployment.yaml")
    assert "/actuator/health/liveness" in content
    assert "/actuator/health/readiness" in content
    assert_no_markers(content)


# ---------------------------------------------------------------------------
# Scaffold type completeness check
# ---------------------------------------------------------------------------

def test_all_types_covered():
    """Ensure every type in ALL_TYPES can be invoked with minimal args (smoke test)."""
    src = SCAFFOLD.read_text(encoding="utf-8")
    match = re.search(r"ALL_TYPES\s*=\s*sorted\(TYPE_CONFIGS\.keys\(\)\)\s*\+\s*\[([^\]]+)\]", src)
    assert match, "Could not find ALL_TYPES definition in scaffold.py"

