# AGENTS.md — {{ project }} GitOps Repository

> **AI agents:** Read this file before working in this repository. It describes the layout, CI/CD patterns, and the AG DevOps plugin conventions used here.

## Repository purpose

This repo deploys the **{{ project }}** application to the BC Government OpenShift Emerald cluster using the `ag-devops` plugin conventions.

## Directory layout

```
.github/
  workflows/
    ci.yml          ← triggers dotnet CI shared workflows
    cd.yml          ← gitops deploy workflow (per environment)
  CODEOWNERS        ← PR approval rules
gitops/
  Chart.yaml        ← Helm umbrella chart (depends on ag-helm-templates)
  values.yaml       ← shared values (all components)
  values-dev.yaml   ← dev environment overrides
  values-test.yaml  ← test environment overrides
  values-prod.yaml  ← prod environment overrides
  templates/        ← generated by scaffold-* skills (ag-helm fragments)
Makefile            ← shortcuts: make render, make lint, make validate
```

## How to add a new component

1. Run `/ag-scaffold` and follow prompts — the agent calls the scaffold-* skills for you.
2. Or run individual commands: `/ag-deployment`, `/ag-service`, `/ag-route`, `/ag-networkpolicy`.
3. Files are written to `gitops/templates/<component>-<kind>.yaml`.
4. Add component values to `gitops/values.yaml` and `values-{dev,test,prod}.yaml`.

## CI/CD

- **CI:** `.github/workflows/ci.yml` triggers shared `.NET 8` composite actions from `ag-devops`.
- **CD:** `.github/workflows/cd.yml` runs `helm upgrade` per environment on merge to `main`.
- **Secrets required:** `OPENSHIFT_SERVER`, `OPENSHIFT_TOKEN` (per environment in GitHub Environments).

## Policy validation

Before pushing, validate rendered manifests:

```bash
make render       # helm template gitops/ > rendered.yaml
make validate     # runs datree + polaris + kube-linter + conftest
```

Or run `/ag-validate` to let the agent do it and explain failures.

## Key constraints

- All Deployments must have `data-class: low|medium|high` label.
- Every component must have a matching NetworkPolicy — no open ingress/egress.
- Routes must use edge TLS termination.
- AVI annotation required on all Route and Ingress resources.

## ag-devops plugin

This repo was bootstrapped with the `ag-devops` plugin. To update templates or re-run scaffolding, ensure the plugin is installed:

```bash
# Install (if not already)
uvx --from git+https://github.com/bcgov-c/ag-devops plugin-add ag-devops

# Re-initialize from scratch (idempotent)
/ag-init
```
